const mockFormValues = {
  familyInfo: {
    user_id: '00uc5s3eotQzTxkyw5d6',
    case_number: 1234,
    phone_one: {
      name: 'Mary Jane',
      number: '111222333',
      safeToLeaveMssg: true,
    },
    phone_two: {
      name: 'Peter Parker',
      number: '111222333',
      safeToLeaveMssg: false,
    },
    emergencyContact: {
      name: 'John Doe',
      number: '111222333',
    },
    vehicle: {
      make: 'Honda',
      year: '1990',
      color: 'black',
      model: 'civic',
      license_plate: '1123',
    },
    last_permanent_address: '3211 East Ave',
    homeless_info: {
      prior_location: '3211 East Ave',
      current_location: 'nowhere',
      num_times_homeless: 5,
      total_len_homeless: '3 months',
      homeless_start_date: '3/5/2018',
      length_at_prior_location: '2 years',
      length_at_current_location: '1 year',
    },
    gov_benefits: {
      RRH: true,
      snap: null,
      cps_fps: null,
      foodstamps: true,
      housing_voucher: null,
      veteran_services: true,
    },
    insurance: {
      pregnancies: {
        is_pregnant: true,
        if_yes_who: 'Mary Jane',
        due_date: '06/15/2021',
      },
      has_insurance: true,
      members_covered: 3,
      health_insurance_type: 'medicaid',
    },
    domestic_violence_info: {
      fleeing_dv: true,
      YWCA_contacted: true,
      has_court_order: true,
      date_last_incident: 'N/A',
      anonymity_preferred: null,
    },
    pets: {
      shelter: true,
      amount: {
        value1: true,
        value2: true,
      },
      dog: true,
      cat: false,
      service_animal: false,
      support_animal: true,
      name_one: 'Rocko',
      name_two: '',
    },
    avatar_url: null,
    percent_complete: 0,
  },
  familyMember: [
    {
      date_of_enrollment: null,
      demographics: {
        first_name: 'John',
        last_name: 'Doe',
        gender: 'Male',
        relationship: 'Partner',
        DOB: null,
        SSN: 1234,
        income: null,
        income_source: {
          job: true,
          TANF: null,
          SSI: null,
          SSDI: null,
          child_support: null,
          other: null,
        },
        race: [
          'Hispanic/Latino',
          'Hispanic/Latino',
          'American Indian or Alaska Native',
          'Hispanic/Latino',
        ],
        ethnicity: null,
        employer: 500,
      },
      barriers: {
        alcohol_abuse: null,
        developmental_disabilities: null,
        chronic_health_issues: null,
        drug_abuse: null,
        HIV_AIDs: null,
        mental_illness: null,
        physical_disabilities: true,
        list_indefinite_conditions: null,
        list_issues: 'Chronic nerve pain in lower back',
      },
      schools: {
        highest_grade_completed: null,
        enrolled_status: null,
        reason_not_enrolled: null,
        attendance_status: null,
        school_type: null,
        school_name: null,
        mckinney_school: null,
      },
      case_members: null,
      flag: null,
      percent_complete: 0,
    },
    {
      date_of_enrollment: null,
      demographics: {
        first_name: 'Jimmy',
        last_name: 'Doe',
        gender: 'Male',
        relationship: 'Child',
        DOB: null,
        SSN: 9876,
        income: null,
        income_source: {
          job: null,
          TANF: null,
          SSI: null,
          SSDI: null,
          child_support: null,
          other: null,
        },
        race: [
          'Hispanic/Latino',
          'Hispanic/Latino',
          'Hispanic/Latino',
          'American Indian or Alaska Native',
        ],
        ethnicity: null,
        employer: 0,
      },
      barriers: {
        alcohol_abuse: null,
        developmental_disabilities: true,
        chronic_health_issues: null,
        drug_abuse: null,
        HIV_AIDs: null,
        mental_illness: null,
        physical_disabilities: null,
        list_indefinite_conditions: 'Learning Disability ',
        list_issues: '',
      },
      schools: {
        highest_grade_completed: '1',
        enrolled_status: true,
        reason_not_enrolled: null,
        attendance_status: 'Regular',
        school_type: 'Public',
        school_name: 'Hard Knocks',
        mckinney_school: null,
      },
      case_members: null,
      flag: null,
      percent_complete: 0,
    },
  ],
};

export default mockFormValues;
